import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <footer
          style={{
            marginTop: 32,
            padding: "20px 16px 32px",
            borderTop: "1px solid #e5e5e5",
            display: "flex",
            justifyContent: "center",
            gap: 18,
            fontSize: 14,
            flexWrap: "wrap",
          }}
        >
          <div style={{ display: "grid", gap: 2, textAlign: "center" }}>
            <div>As an Amazon Associate I earn from qualifying purchases.</div>
            <div>Some links are affiliate links; we may earn a commission at no extra cost to you.</div>
          </div>
          <div style={{ display: "flex", gap: 16, alignItems: "center" }}>
            <Link href="/privacy">Privacy Policy</Link>
            <Link href="/terms">Terms of Use</Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
